[package]
name = "libkv"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
disjoint_impls = "0.8.0"
num-traits.workspace = true
